# allowed its access to every git url
approvedGitRepositories:
    - '**'

# can run scripts like in package.json
enableScripts: true

# Define how Node packages should be installed, disable yarn Plug N play installation strategy
nodeLinker: node-modules

# after which you can use published packages
npmMinimalAgeGate: 0

# should not be ignored by git to maintain same version of yarn
yarnPath: .yarn/releases/yarn-4.18.0.cjs
